[package]
name = "configuration"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
lazy_static = "1.5.0"
serde_json = "1.0.128"
log = { version = "0.4.22", features = [] }
common_lib = { path = "../common_lib" }