[package]
name = "notifications"
version = "0.1.0"
edition = "2021"

[dependencies]
database = { path = "../database" }
crypto = { path = "../crypto" }
lazy_static = "1.5.0"
serde_json = "1.0.132"
serde = { version = "1.0.210", features = ["derive"] }
sqlite = "0.36.1"
num-traits = "0.2.19"