openapi: 3.0.0
info:
  title: openapi
  version: 1.0.0
paths:
  /api/auth/register:
    post:
      summary: Create user
      operationId: Create user
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      requestBody:
        $ref: '#/components/requestBodies/create_user'
  /api/auth/users:
    get:
      summary: Get users
      operationId: Get users
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/auth/login/token:
    post:
      summary: Login with Token
      operationId: Login with Token
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      requestBody:
        $ref: '#/components/requestBodies/login_with_token'
  /api/auth/login:
    post:
      summary: Login
      operationId: Login
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      requestBody:
        $ref: '#/components/requestBodies/login'
  /api/auth/exists:
    get:
      summary: Check if access token exists
      operationId: Check if access token exists
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: token
          in: query
          description: ''
          required: false
          example: ''
  /api/auth/register/generate-access-token:
    post:
      summary: Generate registration access token
      operationId: Generate registration access token
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/auth/register/access-tokens:
    get:
      summary: Get all access tokens
      operationId: Get all access tokens
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/auth/register/validate-access-token:
    post:
      summary: Validate access token
      operationId: Validate access token
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/instances/discover:
    get:
      summary: Discover Instances
      operationId: Discover Instances
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: search
          in: query
          description: ''
          required: true
          example: ''
        - name: sort
          in: query
          description: ''
          required: true
          example: Relevance
        - name: platform
          in: query
          description: ''
          required: true
          example: Modrinth
        - name: limit
          in: query
          description: ''
          required: true
          example: '100'
        - name: offset
          in: query
          description: ''
          required: true
          example: '0'
  /api/java/versions:
    get:
      summary: Get Java Runtime for OS
      operationId: Get Java Runtime for OS
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/java/install/:version/sse:
    post:
      summary: Install Java Version
      operationId: Install Java Version
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: version
          in: query
          description: ''
          required: true
          example: 17.0.1.12.1
  /api/java/versions/:version/files:
    get:
      summary: Get Java Installation Files
      operationId: Get Java Installation Files
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: version
          in: query
          description: ''
          required: true
          example: 16.0.1.9.1
  /api/java/versions/:version/:
    delete:
      summary: Uninstall Java Version
      operationId: Uninstall Java Version
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: version
          in: query
          description: ''
          required: true
          example: 17.0.1.12.1
  /api/minecraft/version/releases/latest:
    get:
      summary: Latest Release
      operationId: Latest Release
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/minecraft/version/snapshots/latest:
    get:
      summary: Latest Snapshot
      operationId: Latest Snapshot
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/minecraft/versions/releases:
    get:
      summary: Releases
      operationId: Releases
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/minecraft/versions/snapshots:
    get:
      summary: Snapshots
      operationId: Snapshots
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/minecraft/versions:
    get:
      summary: Versions
      operationId: Versions
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/minecraft/:version/java:
    get:
      summary: Get Java from Minecraft
      operationId: Get Java from Minecraft
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: version
          in: query
          description: ''
          required: true
          example: '1.17'
  /api/server/supported_loaders:
    get:
      summary: Get Supported Loaders
      operationId: Get Supported Loaders
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/server/:id/backups/create/full:
    post:
      summary: Create Full Manual Backup
      operationId: Create Full Manual Backup
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: gYnxpl9aBABWrZ7N
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
  /api/server/:id/backups/create/incremental:
    post:
      summary: Create Incremental Manual Backup
      operationId: Create Incremental Manual Backup
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: gYnxpl9aBABWrZ7N
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
  /api/server/:id/backups:
    get:
      summary: Get Backups
      operationId: Get Backups
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: gYnxpl9aBABWrZ7N
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: ''
  /api/server:
    post:
      summary: Create a new server
      operationId: Create a new server
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JDhvajJ5TWYxcEZvcGlBZGFQWjgvbnVaTzhaMmZ5aWdBeEtFdFdXRUMvVXFoTFZvZHNtYk0yIiwidXNlcm5hbWUiOiJhZG1pbiJ9
      requestBody:
        $ref: '#/components/requestBodies/create_a_new_server'
    get:
      summary: Get servers list
      operationId: Get servers list
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
  /api/server/:id:
    get:
      summary: Get server by Id
      operationId: Get server by Id
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: ''
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
  /api/server/:id/properties:
    get:
      summary: Get Properties
      operationId: Get Properties
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: ''
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFkxRmpaQUwyNU9SMDF6Y2tSZXNaTGVYalNKbmtxQTlUV2FCc2t5SkFicGZSVm4yRjdueUkyIiwidXNlcm5hbWUiOiJhZG1pbiJ9
  /api/server/:id/properties/:key:
    post:
      summary: Set Property
      operationId: Set Property
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: key
          in: query
          description: ''
          required: true
          example: ''
        - name: id
          in: query
          description: ''
          required: true
          example: ''
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFkxRmpaQUwyNU9SMDF6Y2tSZXNaTGVYalNKbmtxQTlUV2FCc2t5SkFicGZSVm4yRjdueUkyIiwidXNlcm5hbWUiOiJhZG1pbiJ9
      requestBody:
        content:
          text/plain:
            schema:
              type: string
  /api/server/:id/files:
    post:
      summary: Get Server Files
      operationId: Get Server Files
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: gYnxpl9aBABWrZ7N
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
      requestBody:
        content:
          text/plain:
            schema:
              type: string
  /api/server/:id/settings:
    get:
      summary: Get Settings
      operationId: Get Settings
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: ''
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
  /api/server/:id/settings/executable:
    post:
      summary: Set Executable
      operationId: Set Executable
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: ''
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
      requestBody:
        content:
          text/plain:
            schema:
              type: string
  /api/server/:id/settings/server-name:
    post:
      summary: Set Server Name
      operationId: Set Server Name
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: ''
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
      requestBody:
        content:
          text/plain:
            schema:
              type: string
  /api/server/:id/settings/args/java:
    post:
      summary: Set Java Arguments
      operationId: Set Java Arguments
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: ''
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
      requestBody:
        content:
          text/plain:
            schema:
              type: string
  /api/server/:id/settings/args/minecraft:
    post:
      summary: Set Minecraft Arguments
      operationId: Set Minecraft Arguments
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: ''
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
      requestBody:
        content:
          text/plain:
            schema:
              type: string
  /api/server/:id/settings/memory/max:
    post:
      summary: Set Memory Max
      operationId: Set Memory Max
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: ''
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
      requestBody:
        content:
          text/plain:
            schema:
              type: string
  /api/server/:id/settings/memory/min:
    post:
      summary: Set Memory Min
      operationId: Set Memory Min
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: ''
        - name: X-Authorization-Token
          in: header
          description: ''
          required: true
          example: >-
            eyJoYXNoIjoiJDJiJDA0JFd5LmNOQlRCQ0luaGJ2TjcvQUNPYU9Mb1VZVnlMNXgyb3NubjFkNEFxQ2kzTzVhcUJMUXhPIiwidXNlcm5hbWUiOiJhZG1pbiJ9
      requestBody:
        content:
          text/plain:
            schema:
              type: string
  /api/system/storage:
    get:
      summary: Get storage information
      operationId: Get storage information
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/system:
    get:
      summary: Get system information
      operationId: Get system information
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
  /api/system/usage:
    get:
      summary: Get system usage
      operationId: Get system usage
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
servers:
  - url: http://127.0.0.1:1420
components:
  schemas:
    create_user:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
    login_with_token:
      type: object
      properties:
        token:
          type: string
    login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    create_a_new_server:
      type: object
      properties:
        name:
          type: string
        port:
          type: number
        difficulty:
          type: string
        gamemode:
          type: string
        hardcore:
          type: boolean
        max_players:
          type: number
        minecraft_version:
          type: string
        loader:
          type: number
        loader_version:
          type: string
  requestBodies:
    create_user:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_user'
      description: ''
      required: true
    login_with_token:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/login_with_token'
      description: ''
      required: true
    login:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/login'
      description: ''
      required: true
    create_a_new_server:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_a_new_server'
      description: ''
      required: true
  securitySchemes: {}
