[package]
name = "archive_utility"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.5.0"
zip = { version = "2.2.0" }
log = "0.4.22"
rayon = "1.10.0"